# Generated by Django 5.1.6 on 2025-03-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_categoria_tienda_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
