# Generated by Django 5.1.6 on 2025-03-18 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='title',
            new_name='nombre',
        ),
    ]
